variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/siteconf

test:
  tags:
    - firmware
  script:
    - pwd
    - echo $CI_BUILDS_DIR
    - echo $GIT_CLONE_PATH
    - git clone https://github.com/freifunk-gluon/gluon.git . -b v2018.2.x
    - mv $GIT_CLONE_PATH .
    - ls
    - ls site