stages:
    - build
    - test

build:
    - stage: build
    - echo building
    - mkdir build
    - touch build/test.txt
    
test:
    - stage: test
    - echo testing
    - test -f build/test.txt
