variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/2c952829/0/gluon/site

stages:
  - dependencies
  - build
  - test
  - cleanup

dependencies:
  stage: dependencies
  tags:
    - firmware
  before_script: 
    - cd ..
    - if [ $(git status | grep -c am) -gt 0 ];then echo "am running"; git am --show-current-patch;git am --abort;else echo "not running";fi
    - cd site
  script:
#    - bash ./buildscript.sh clean_patches
#    - bash ./buildscript.sh update_patches
    - bash ./buildscript.sh patch
    - bash ./buildscript.sh prepare GLUON_BRANCH nightly_master
    - bash ./buildscript.sh prepare GLUON_RELEASE $(date +%Y%m%d)
    - bash ./buildscript.sh prepare l2tp

#build:
#  stage: build
#  script:
#    - bash ./buildscript.sh
#    
#.test:
#  stage: test
#  script:
#    - echo testing
#    - test -f build/test.txt

cleanup:
  stage: cleanup
  script:
    - bash ./buildscript.sh clean_patches

