variables:
  GLUON_BRANCH: "nightly"

stages:
  - prepare
  - build
  - sign
  - deploy

prepare-job:
  stage: prepare
  tags:
    - firmware
  script:
  - bash build/before.sh

ar71xx-generic:
  stage: build
  tags:
    - firmware
  script:
    - bash build/build-ar71xx-generic.sh

#ar71xx-nand:
#  stage: build
#  tags:
#    - firmware
#  script:
#    - bash build/build-ar71xx-nand.sh

sign:
  stage: deploy
  tags:
    - firmware
  script:
    - bash build/sign.sh

deploy:
  stage: deploy
  tags:
    - firmware
  script:
    - bash build/deploy.sh
