variables:
  GLUON_BRANCH: "nightly"

before_script:
  - bash build/before.sh

stages:
  - build
  - sign
  - deploy

ar71xx-generic:
  stage: build
  tags:
    - firmware
  script:
    - bash build/build-ar71xx-generic.sh
    
#ar71xx-nand:
#  stage: build
#  tags:
#    - firmware
#  script:
#    - bash build/build-ar71xx-nand.sh
    
sign:
  stage: deploy
  tags:
    - firmware
  script:
    - bash build/sign.sh
    
deploy:
  stage: deploy
  tags:
    - firmware
  script:
    - bash build/deploy.sh
