variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/2c952829/0/gluon/site

stages:
  - dependencies
  - build
  - test

dependencies:
  stage: dependencies
  tags:
    - firmware
  script:
    - bash ./buildscript.sh clean_patches
    - bash ./buildscript.sh update_patches
    - bash ./buildscript.sh patch
    - bash ./buildscript.sh prepare GLUON_BRANCH nightly_master
    - bash ./buildscript.sh prepare GLUON_RELEASE $(date +%Y%m%d)
    - bash ./buildscript.sh prepare l2tp

#build:
#  stage: build
#  script:
#    - bash ./buildscript.sh
#    
#.test:
#  stage: test
#  script:
#    - echo testing
#    - test -f build/test.txt



