variables:
  GLUON_BRANCH: "nightly_master"
  ECDSA_PRIVAT_KEY: "d8b6b90da391e2b8fdf1fec1499539937a35abcea79f2c3c15ae2f9edb5c455f"
  GLUON_VERSION: "v2016.2.x"

stages:
  - build
  - sign
  - deploy

build:gluon:
  stage: build
  only:
    - master
    - citest
  tags:
    - firmware
  script:
    - bash .build/build.sh $GLUON_BRANCH $GLUON_VERSION
  artifacts:
    paths:
      - output/images/factory/gluon-ffnw-*
      - output/images/sysupgrade/$GLUON_BRANCH.manifest
      - output/images/sysupgrade/gluon-ffnw-*
      - contrib/

sign:
  stage: sign
  only:
    - master
    - citest
  tags:
    - firmware
  script:
    - bash .build/sign.sh $GLUON_BRANCH $ECDSA_PRIVAT_KEY
  dependencies:
    - build:gluon
  artifacts:
    paths:
      - output/images/

deploy:
  stage: deploy
  only:
    - master
    - citest
  tags:
    - firmware
  script:
    - bash .build/deploy.sh $GLUON_BRANCH $CI_BUILD_REF_NAME
  dependencies:
    - sign
