variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/siteconf

test:
  tags:
    - firmware
  script:
    - pwd
    - echo $CI_BUILDS_DIR
    - echo $GIT_CLONE_PATH
    - git clone https://github.com/freifunk-gluon/gluon.git $CI_BUILDS_DIR/freifunk_build -b v2018.2.x
    - cd $CI_BUILDS_DIR/freifunk_build
    - mv $GIT_CLONE_PATH ./site
    - mv $CI_BUILDS_DIR/freifunk_build $GIT_CLONE_PATH
    - cd $GIT_CLONE_PATH/site
    - ./buildscript.sh patch
    - ./buildscript.sh prepare GLUON_BRANCH testing
    - ./buildscript.sh prepare GLUON_RELEASE $(date +%Y%m%d)
    - ./buildscript.sh prepare l2tp
