variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/2c952829/0/gluon/site

stages:
  - dependencies
  - build
  - test

dependencies:
  stage: dependencies
  tags:
    - firmware
  before_script: 
    - cd ..
    - git am show-curent-patch
  script:
    - ./buildscript.sh clean_patches
    - ./buildscript.sh update_patches
    - ./buildscript.sh patch
    - ./buildscript.sh prepare GLUON_BRANCH nightly_master
    - ./buildscript.sh prepare GLUON_RELEASE $(date +%Y%m%d)
    - ./buildscript.sh prepare l2tp

#build:
#  stage: build
#  script:
#    - bash ./buildscript.sh
#    
#.test:
#  stage: test
#  script:
#    - echo testing
#    - test -f build/test.txt



